apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: app-image
    newName: <YOUR_ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com/blue-green-demo-repo
    newTag: latest