apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
- name: app-image
  newName: 253906287264.dkr.ecr.eu-west-1.amazonaws.com/argocd-app-demo-repo
  newTag: 2730d1e
